service: aws-python

provider:
  name: aws
  runtime: python3.9
  versionFunctions: false
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  tracing:
    apiGateway: true
    lambda: true

custom:
  customDomain:
    domainName: api.kindergartenil.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  cognitoAuthorizerArn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/${aws:region}_PokjeshX3
  pythonRequirements:
    dockerizePip: non-linux
    usePipenv: false

functions:
  GetChildData:
    handler: lambdas/children/get_child_data_lambda.get_child_data
    role: ChildrenRole
    events:
      - http:
          path: children-mock
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/children/**'

  AddChildData:
    handler: lambdas/children/add_child_data_lambda.add_child_data
    role: ChildrenRole
    events:
      - http:
          path: children-mock
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/children/**'

  GetTeacherData:
    handler: lambdas/teacher/get_teacher_data_lambda.get_teacher_data
    role: TeacherRole
    events:
      - http:
          path: teacher
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/teacher/**'

  UpdateTeacherData:
    handler: lambdas/signup/signup_teacher_lambda.signup_teacher
    role: TeacherRole
    events:
      - http:
          path: teacher/signup
          method: put
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/teacher/**'

  CogintoPostConfirmation:
    handler: lambdas/cognito/cognito_post_confirmation_add_teacher_data_lambda.add_teacher_data
    role: TeacherRole
    package:
      patterns:
        - 'lambdas/cognito/**'

  GetKindergartenDataMock:
    handler: lambdas/kindergarten/get_kindergarten_data_lambda_mock.get_kindergarten_data
    role: KindergartenRole
    events:
      - http:
          path: kindergarten-mock
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/kindergarten/**'

  GetKindergartenData:
    handler: lambdas/kindergarten/get_kindergarten_data_lambda.get_kindergarten_data
    role: KindergartenRole
    events:
      - http:
          path: kindergarten
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}

    package:
      patterns:
        - 'lambdas/kindergarten/**'

  GetAttendanceData:
    handler: lambdas/attendance/get_attendance_data_lambda.get_attendance_data
    role: AttendanceRole
    events:
      - http:
          path: attendance-mock
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/attendance/**'

  AddAttendanceData:
    handler: lambdas/attendance/add_attendance_data_lambda.add_attendance_data
    role: AttendanceRole
    events:
      - http:
          path: attendance-mock
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/attendance/**'

plugins:
  - serverless-dependson-plugin
  - serverless-python-requirements
  - serverless-plugin-stage-variables
  - serverless-domain-manager
resources:
  # roles
  - ${file(resources/iam/AttendanceRole.yml)}
  - ${file(resources/iam/ChildrenRole.yml)}
  - ${file(resources/iam/KindergartenRole.yml)}
  - ${file(resources/iam/TeacherRole.yml)}
  # dynamodb
  - ${file(resources/dynamodb/AttendanceData.yml)}
  - ${file(resources/dynamodb/ChildData.yml)}
  - ${file(resources/dynamodb/KindergartenData.yml)}
  - ${file(resources/dynamodb/TeacherData.yml)}

  # cognito
#  - ${file(resources/cognito/Kindergarten-02.yml)}
package:
  patterns:
    - '!node_modules/**'
    - '!lambdas/**'
    - '!tests/**'
    - '!resources/**'
    - 'lambdas/__init__.py'
    - 'shared/**'
    - 'utils/**'

  individually: true


