service: aws-python

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'us-east-1'}
  websocketApiName: live-dynamodb-api
  websocketApiRouteSelectionExpression: $request.body.action
  tracing:
    apiGateway: true
    lambda: true
  environment:
    SLACK_ALERTS_WEBHOOK: ${self:custom.environment.SLACK_ALERTS_WEBHOOK}
    SLACK_REGISTER_WEBHOOK: ${self:custom.environment.SLACK_REGISTER_WEBHOOK}
    S3_UPLOAD_AWS_ACCESS_KEY_ID: ${self:custom.environment.S3_UPLOAD_AWS_ACCESS_KEY_ID}
    S3_UPLOAD_AWS_SECRET_ACCESS_KEY: ${self:custom.environment.S3_UPLOAD_AWS_SECRET_ACCESS_KEY}

custom:
  customDomain:
    rest:
      domainName: api.kindergartenil.com
      basePath: ''
      stage: ${self:provider.stage}
      createRoute53Record: true
      endpointType: edge
    websocket:
      domainName: websocket.kindergartenil.com
      basePath: ''
      stage: ${self:provider.stage}
      createRoute53Record: true
      endpointType: regional
  cognitoAuthorizerArn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/${aws:region}_PokjeshX3
  cognitoAuthorizerName: Kindergarten-02
  pythonRequirements:
    dockerizePip: true
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}

functions:
  GetChildData:
    handler: lambdas/children/get_child_data_lambda.get_child_data
    role: GetChildDataRole
    events:
      - http:
          path: children
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/children/**'

  UpdateChildGroupName:
    handler: lambdas/children/update_child_group_name_lambda.update_child_group_name
    role: UpdateChildGroupNameRole
    events:
      - http:
          path: children/update_group_name
          method: PUT
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/children/**'


  AddChildData:
    handler: lambdas/children/add_child_data_lambda.add_child_data
    role: AddChildDataRole
    events:
      - http:
          path: children
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/children/**'

  DeleteChildData:
    handler: lambdas/children/delete_child_data_lambda.delete_child_data
    role: AddChildDataRole
    events:
      - http:
          path: children/delete
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/children/**'

  UploadChildPhoto:
    handler: lambdas/children/get_upload_link_lambda.get_upload_link
    role: UploadChildPhotoRole
    events:
      - http:
          path: child/upload_photo_link
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/children/**'

  GetTeacherData:
    handler: lambdas/teacher/get_teacher_data_lambda.get_teacher_data
    role: GetTeacherDataRole
    events:
      - http:
          path: teacher
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/teacher/**'

  UpdateTeacherGroupName:
    handler: lambdas/teacher/update_teacher_group_name_lambda.update_teacher_group_name
    role: UpdateTeacherGroupNameRole
    events:
      - http:
          path: teacher/update_group_name
          method: PUT
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/teacher/**'

  UpdateTeacherData:
    handler: lambdas/signup/signup_teacher_lambda.signup_teacher
    role: UpdateTeacherDataRole
    events:
      - http:
          path: teacher/signup
          method: put
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/signup/**'
        -
  UpdateTeacherName:
    handler: lambdas/teacher/update_teacher_name_lambda.update_teacher_name
    role: UpdateTeacherNameRole
    events:
      - http:
          path: teacher/update_name
          method: PUT
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/teacher/**'


  UploadTeacherPhoto:
    handler: lambdas/teacher/get_upload_link_lambda.get_upload_link
    role: UploadTeacherPhotoRole
    events:
      - http:
          path: teacher/upload_photo_link
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/teacher/**'

  CogintoPostConfirmation:
    handler: lambdas/cognito/cognito_post_confirmation_add_teacher_or_parent_data_lambda.add_teacher_or_parent
    role: CogintoPostConfirmationRole
#    events:
#      - cognitoUserPool:
#          pool: ${self:custom.cognitoAuthorizerName}
#          trigger: PostConfirmation
#          forceDeploy: true
    package:
      patterns:
        - 'lambdas/cognito/**'

  GetKindergartenData:
    handler: lambdas/kindergarten/get_kindergarten_data_lambda.get_kindergarten_data
    role: GetKindergartenDataRole
    events:
      - http:
          path: kindergarten/info
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/kindergarten/**'

  GetIsKindergartenIdExist:
    handler: lambdas/kindergarten/kindergarten_exist_lambda.kindergarten_exist
    role: GetIsKindergartenIdExistRole
    events:
      - http:
          path: kindergarten/exist
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
    package:
      patterns:
        - 'lambdas/kindergarten/**'

  GetKindergartenChildren:
    handler: lambdas/kindergarten/get_kindergarten_children_lambda.get_kindergarten_children
    role: GetKindergartenChildrenRole
    events:
      - http:
          path: kindergarten/group_chidren
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/kindergarten/**'

  GetChildAttendance:
    handler: lambdas/attendance/get_child_attendance.get_child_attendance
    role: AddAttendanceDataRole
    events:
      - http:
          path: attendance
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/attendance/**'

  GetKindergartenGroups:
    handler: lambdas/groups/get_kindergarten_groups_lambda.get_kindergarten_groups
    role: GetGroupDataRole
    events:
      - http:
          path: groups
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/groups/**'

  AddKindergartenGroup:
    handler: lambdas/groups/add_kindergarten_group_lambda.add_kindergarten_group
    role: AddGroupDataRole
    events:
      - http:
          path: groups
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/groups/**'

  DeleteKindergartenGroup:
    handler: lambdas/groups/delete_kindergarten_group_lambda.delete_kindergarten_group
    role: DeleteGroupDataRole
    events:
      - http:
          path: groups/delete
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/groups/**'

  GetKindergartenAttendanceSpreadsheet:
    handler: lambdas/kindergarten/get_attendance_spreadsheet.get_attendance_spreadsheet
    role: GetKindergartenChildrenRole
    events:
      - http:
          path: kindergarten/attendance_spreadsheet
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./response_apigateway_csv.yml)}
          response: ${file(./response_apigateway_csv.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/kindergarten/**'

  AddAttendanceData:
    handler: lambdas/attendance/add_attendance_data_lambda.add_attendance_data
    role: AddAttendanceDataRole
    events:
      - http:
          path: attendance
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/attendance/**'

  GetParentData:
    handler: lambdas/parent/get_parent_data_lambda.get_parent_data
    role: AddAttendanceDataRole
    events:
      - http:
          path: parent
          method: get
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/parent/**'

  AddParentChildAttendance:
    handler: lambdas/parent/add_child_attendance_lambda.add_child_attendance
    role: AddAttendanceDataRole
    events:
      - http:
          path: parent/attendance
          method: post
          integration: lambda
          cors: true
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: ${self:custom.cognitoAuthorizerArn}
    package:
      patterns:
        - 'lambdas/parent/**'

  connectHandler:
    handler: lambdas/websocket/connect_lambda.connect
    role: WebsocketRole
    events:
      - websocket:
          route: $connect
    package:
      patterns:
        - 'lambdas/websocket/**'

  disconnectHandler:
    handler: lambdas/websocket/disconnect_lambda.disconnect
    role: WebsocketRole
    events:
      - websocket:
          route: $disconnect
    package:
      patterns:
        - 'lambdas/websocket/**'

  AttandanceDataStream:
    handler: lambdas/websocket/dynamodb_stream_lambda.send_message
    role: AttandanceDataStreamRole
    #    events:
    #      - stream:
    #          arn: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/AttendanceData/stream/2022-03-10T22:55:54.027
    package:
      patterns:
        - 'lambdas/websocket/**'

plugins:
  - serverless-python-requirements
  - serverless-plugin-stage-variables
  - serverless-domain-manager
resources:
  # roles
  - ${file(resources/iam/GetGroupDataRole.yml)}
  - ${file(resources/iam/DeleteGroupDataRole.yml)}
  - ${file(resources/iam/AddGroupDataRole.yml)}
  - ${file(resources/iam/GetChildDataRole.yml)}
  - ${file(resources/iam/AddChildDataRole.yml)}
  - ${file(resources/iam/UpdateChildGroupNameRole.yml)}
  - ${file(resources/iam/UpdateTeacherGroupNameRole.yml)}
  - ${file(resources/iam/UploadChildPhotoRole.yml)}
  - ${file(resources/iam/GetTeacherDataRole.yml)}
  - ${file(resources/iam/UpdateTeacherDataRole.yml)}
  - ${file(resources/iam/UploadTeacherPhotoRole.yml)}
  - ${file(resources/iam/UpdateTeacherNameRole.yml)}
  - ${file(resources/iam/CogintoPostConfirmationRole.yml)}
  - ${file(resources/iam/GetKindergartenDataRole.yml)}
  - ${file(resources/iam/GetKindergartenChildrenRole.yml)}
  - ${file(resources/iam/GetIsKindergartenIdExistRole.yml)}
  - ${file(resources/iam/AddAttendanceDataRole.yml)}
  - ${file(resources/iam/WebsocketRole.yml)}
  - ${file(resources/iam/AttandanceDataStreamRole.yml)}
  # dynamodb
  - ${file(resources/dynamodb/AttendanceData.yml)}
  - ${file(resources/dynamodb/ChildData.yml)}
  - ${file(resources/dynamodb/KindergartenData.yml)}
  - ${file(resources/dynamodb/TeacherData.yml)}
  - ${file(resources/dynamodb/GroupsData.yml)}
  - ${file(resources/dynamodb/ParentData.yml)}
  #  - ${file(resources/dynamodb/Websocket.yml)}

  # cognito
#  - ${file(resources/cognito/Kindergarten-02.yml)}
package:
  patterns:
    - '!node_modules/**'
    - '!lambdas/**'
    - '!tests/**'
    - '!resources/**'
    - '!env.yml'
    - 'lambdas/__init__.py'
    - 'shared/**'
    - 'utils/**'
    - 'lambdas/**'
#  individually: true


