Resources:
  ChildData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "child_id"
          AttributeType: "S"
        - AttributeName: "kindergarten_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "child_id"
          KeyType: "HASH"
        - AttributeName: "kindergarten_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "ChildData"
