Resources:
  GroupsData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "kindergarten_id"
          AttributeType: "S"
        - AttributeName: "group_name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "kindergarten_id"
          KeyType: "HASH"
        - AttributeName: "group_name"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "GroupsData"
