Resources:
  KindergartenData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "kindergarten_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "kindergarten_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "KindergartenData"
