Resources:
  TeacherData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "phone_number"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "phone_number"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "TeacherData"

