Resources:
  WebsocketConnectionManager:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "kindergarten_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "kindergarten_id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: connectionIndex
          AttributeDefinitions:
            - AttributeName: "connection_id"
              AttributeType: "S"
          KeySchema:
            - AttributeName: "connection_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: "True"
      TableName: "WebsocketConnectionManager"