Resources:
  WebsocketConnectionManager01:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "kindergarten_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "kindergarten_id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: connectionIndex
          KeySchema:
            - AttributeName: "connection_id"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: "True"
      TableName: "WebsocketConnectionManager"