name: Deploy_prod

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Create env file
        run: |
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1
      - name: Serverless Deploy
        run: npm run-script deploy
  E2E:
    needs: deploy
    name: E2E
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.x
    strategy:
      matrix:
        python-version:
          - 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest moto
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run E2E
        run: pytest E2E -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SLACK_ALERTS_WEBHOOK: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
          SLACK_REGISTER_WEBHOOK: ${{ secrets.SLACK_REGISTER_WEBHOOK }}
          S3_UPLOAD_AWS_ACCESS_KEY_ID: ${{ secrets.S3_UPLOAD_AWS_ACCESS_KEY_ID }}
          S3_UPLOAD_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_UPLOAD_AWS_SECRET_ACCESS_KEY }}
