name: Deploy

on: [pull_request,workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Create env file
        run: |
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Serverless Deploy
        run: npm run-script deploy
      - name: run E2E
        run: pytest E2E
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SLACK_ALERTS_WEBHOOK: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
          SLACK_REGISTER_WEBHOOK: ${{ secrets.SLACK_REGISTER_WEBHOOK }}
          S3_UPLOAD_AWS_ACCESS_KEY_ID: ${{ secrets.S3_UPLOAD_AWS_ACCESS_KEY_ID }}
          S3_UPLOAD_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_UPLOAD_AWS_SECRET_ACCESS_KEY }}
